<form action="" method="" class="">
  <div class="form-bg from-wrapper radius-33 bg-img-cover img-img-no-repeat w-100 position-center">
    <div class="mb-3 form-group">
      <i class="fa-solid fa-user icon"></i>
      <input type="text" class="form-control" placeholder="Enter Full Name">
    </div>
    <div class="mb-3 form-group">
      <i class="fa-solid fa-phone icon"></i>
      <input type="number" class="form-control" placeholder="Phone Number">
    </div>
    <div class="mb-3 form-group">
      <i class="fa-solid fa-car icon"></i>
      <input type="text" class="form-control" placeholder="Make">
    </div>
    <div class="mb-3 form-group">
      <i class="fa-solid fa-car-side icon"></i>
      <input type="text" class="form-control" placeholder="Model/Variant">
    </div>
    <div class="mb-3 form-group">
      <i class="fa-solid fa-tools icon"></i>
      <select class="form-select">
        <option disabled selected value="">Select Services</option>
        <option value="Auto-Spa">Auto Spa</option>
        <option value="Car-Inspection">Car Inspection</option>
        <option value="Car-Wrapping">Car Wrapping</option>
        <option value="Ceramic">Ceramic</option>
        <option value="Chinese-Car">Chinese Car</option>
        <option value="Electric-Car">Electric Car</option>
        <option value="Electric-Repair">Electric Repair</option>
        <option value="Extended-Warranty">Extended Warranty</option>
        <option value="General-Repair">General Repair</option>
        <option value="Major">Major Services</option>
        <option value="Minor">Minor Services</option>
        <option value="Road-Side-Assistance">Road Side Assistance</option>
        <option value="Tinting">Tinting</option>
      </select>
    </div>
    <div class="mb-3 form-group">
      <i class="fa-solid fa-map-marker-alt icon"></i>
      <input type="text" class="form-control" placeholder="Location">
    </div>
  </div>
  <div class="form-btn-wrap text-center">
    <button type="submit" class="btn radius-100 text-center">
      <i class="fa-solid fa-angle-right"></i>
    </button>
  </div>
</form>